# this makefile is for cross compiling injection C files in a directory for emulation

include defaultEnvUnix.mk

TARGETS := $(patsubst ./%.c, ./%.riscv, $(wildcard ./test_inj_*.c))

all: $(TARGETS)

# Compiling
%o: %.c
	$(CC) -c -o $@ $(CFLAGS) $<

# Linking
%.riscv: inj_unix_helpers.o %.o
	$(LD) -o $@ $(LDFLAGS) $^

clean:
	rm -f *.o *.riscv

.PHONY: clean all
