name: fett-target:ci
description: ""
inputs:
  ssh-key:
    required: true
    description: ""
  run:
    required: true
    description: ""
  image:
    required: false
    description: ""
    default: "artifactory.galois.com:5008/fett-target:ci"
runs:
  using: node12
  main: index.js
