#!/usr/bin/env python3

import argparse
import uuid
import subprocess

parser = argparse.ArgumentParser(description='Generate a cert using the FETT CA')
parser.add_argument("--name", required=True, help="Optional cert name")

def gen_cert(name):

    print("Generating cert for %s" % name)
    key_name = "%s.key" % name
    csr_name = "%s.csr" % name
    crt_name = "%s.crt" % name
    subj = "/C=US/ST=OR/L=Portland/O=Galois, Inc/CN=localhost"
    # Private Key
    subprocess.call(['openssl', 'genrsa', '-out', key_name, '2048'])
    # Certificate Signing Request
    subprocess.call(['openssl', 'req', '-new', '-key', key_name, '-out', csr_name,
    '-subj', subj])
    # Certificate
    subprocess.call(['openssl', 'x509', '-req', '-in', csr_name, '-CA', 'fettCA.pem',
        '-CAkey', 'fettCA.key', '-CAcreateserial', '-out', crt_name, '-days', '825',
         '-sha256']
    )

if __name__ == "__main__":
    args = parser.parse_args()
    gen_cert(args.name)
