#!/usr/bin/env python3

import argparse
import uuid
import subprocess

parser = argparse.ArgumentParser(description='Generate a cert using the FETT CA')
parser.add_argument("--name", required=True, help="Optional cert name")
parser.add_argument("--app", required=False, help="Optional app suffix")
parser.add_argument("--pass", dest="passw", required=True, help="CA Key Passphrase")

def gen_cert(name, app, passw):

    print("Generating cert for %s" % name)
    if(app):
        name = "%s-%s" % (name, app)
    key_name = "%s.key" % name
    csr_name = "%s.csr" % name
    crt_name = "%s.crt" % name
    subj = "/C=US/ST=OR/L=Portland/O=Galois, Inc/CN=%s" % name
    # Private Key
    subprocess.call(['openssl', 'genrsa', '-out', key_name, '2048'])
    # Certificate Signing Request
    subprocess.call(['openssl', 'req', '-new', '-key', key_name, '-out', csr_name,
    '-subj', subj])
    # Certificate
    process = subprocess.Popen(['openssl', 'x509', '-req', '-in', csr_name, '-CA', 'fettCA.pem',
        '-CAkey', 'fettCA.key', '-CAcreateserial', '-out', crt_name, '-days', '825',
         '-sha256', '-passin', 'stdin'],
        stdin = subprocess.PIPE,
        stdout = subprocess.PIPE,
        stderr = subprocess.PIPE,
        encoding = "utf8",
        shell=False
    )
    process.communicate("%s\n" % passw)

if __name__ == "__main__":
    args = parser.parse_args()
    gen_cert(args.name, args.app, args.passw)
