name: fett-target:ci
description: ""
runs:
  using: docker
  # This works because the VM with the self hosted runner has already pulled the image.
  image: docker://artifactory.galois.com:5008/fett-target:ci
  args:
    - ${{ inputs.run }}
