name: fett-target:ci
description: ""
inputs:
  run:
    required: true
    description: ""
runs:
  using: docker
  # This works because the VM with the self hosted runner has already pulled the image.
  image: docker://artifactory.galois.com:5008/fett-target:ci
  env:
    HOME: /home/besspinuser
  args:
    - bash
    - -c
    - ${{ inputs.run }}
