name: fett-target:ci
description: ""
inputs:
  ssh-key:
    required: true
    description: ""
  run:
    required: true
    description: ""
runs:
  using: docker
  # This works because the VM with the self hosted runner has already pulled the image.
  image: docker://artifactory.galois.com:5008/fett-target:ci
  # HOME needs to be overridden locally because github overrides it and nix-shell requires it.
  entrypoint: ./entrypoint.sh
  args:
    - bash
    - -c
    - |
      export HOME=/home/besspinuser
      export PATH=/opt/Xilinx/Vivado/2019.1/bin:/opt/Xilinx/Vivado_Lab/2019.1/bin:$PATH
      . /opt/Xilinx/Vivado_Lab/2019.1/settings64.sh
      eval $(ssh-agent -s)
      ssh-add <(echo "${{ inputs.ssh-key }}")
      . /home/besspinuser/.nix-profile/etc/profile.d/nix.sh
      ${{ inputs.run }}
