##
##
##
STORE       ?= flatstore
INTERPRETER ?= binterpreter
TEST        ?= atoi
PARAMETERS  ?= include/parameters

#STORE_SIZE ?= 3
#NDOMAINS   ?= 2
DEBUG      ?= 0

ifeq ($(DEBUG),1)
	override CFLAGS += -DDEBUG
	override CFLAGS += -g
endif

HEADERS = $(wildcard include/*.h) $(PARAMETERS)/parameters.h
SOURCES = stores/$(STORE).c \
          interpreters/$(INTERPRETER).c \
          control/control.c \
          tests/$(TEST).c

FSOURCES = $(wildcard functions/*.c)
FOBJS    = $(FSOURCES:.c=.o)

OBJS = $(SOURCES:.c=.o)

override CFLAGS += -I include
override CFLAGS += -I $(PARAMETERS)

$(info BUILDING TEST:)
$(info STORE=$(STORE))
$(info INTERPRETER=$(INTERPRETER))
$(info TEST=$(TEST))

WRAPPER=$(TEST)_$(STORE)_$(INTERPRETER)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

weakness: $(SOURCES) $(HEADERS) $(FOBJS)
	$(CC) $(CFLAGS) $(SOURCES) $(FOBJS) -o $(TEST)_$(STORE)_$(INTERPRETER).riscv

testgen_weakness: $(SOURCES) $(HEADERS) $(FOBJS)
	$(CC) $(CFLAGS) $(SOURCES) $(FOBJS) $(WRAPPER).c -o $(WRAPPER).riscv

export TARGETS=weakness
