#
# Helpful for debugging
#

CFLAGS += -fsanitize=address,undefined
CFLAGS += -Wno-format-security -I lib -g 

SOURCES = $(wildcard test_*.c)

%.o: %.c
	clang -c $(CFLAGS) $< -o $@

test_%: test_%.o lib/target_observer_harness.o
	clang $(CFLAGS) lib/target_observer_harness.o $< -o $@

tests: $(SOURCES:.c=)

clean:
	rm -f $(SOURCES:.c=) lib/target_observer_harness.o
