name: CI DevPR
on:
  pull_request:
    branches:
      - develop

jobs:
  DevPR:
    runs-on: docker-fpga
    strategy:
      fail-fast: false
      matrix:
        cfg: [1, 2, 3, 4]

    steps:
      - name: Remove lock file if it exists to prevent git fetch failures
        run: find .git -name index.lock -print -exec rm -f {} +
        continue-on-error: true
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          lfs: true
      - uses: ./.github/action
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          run: nix-shell --command "./ci/fett-ci.py runDevPR -ep OnPrem -art devPR-${{ github.sha }} -i ${{ matrix.cfg }}"
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: devPR-${{ github.sha }}
          path: "*-devPR-${{ github.sha }}"
