"""Cyberphys Component IDs
Project: SSITH CyberPhysical Demonstrator
Name: ../cyberphyslib/cyberphyslib/canlib/componentids.py
Author: Steven Osborn <steven@lolsborn.com>, Kristofer Dobelstein, Ethan Lew <elew@galois.com>
Michal Podhradsky <mpodhradsky@galois.com>
Date: 31 August 2021
This file was created by BESSPIN-Tool-Suite/besspin/cyberPhys/canlib/make_can_spec.py
"""

BUTTON_STATION_1 = 0x01 # Buttom press on infotainment UI
BUTTON_STATION_2 = 0x02 # Buttom press on infotainment UI
BUTTON_STATION_3 = 0x03 # Buttom press on infotainment UI
BUTTON_VOLUME_DOWN = 0x10 # Buttom press on infotainment UI
BUTTON_VOLUME_UP = 0x11 # Buttom press on infotainment UI
SCENARIO_BASELINE = 0x12 # Type of scenario
SCENARIO_SECURE_INFOTAINMENT = 0x13 # Type of scenario
SCENARIO_SECURE_ECU = 0x14 # Type of scenario
FUNCTIONALITY_NONE = 0x15 # Not even base components are running
FUNCTIONALITY_MINIMAL = 0x16 # No FPGAs
FUNCTIONALITY_MEDIUM = 0x17 # Only ECUs
FUNCTIONALITY_FULL = 0x18 # Full functionality, including infotainment
BESSPIN_TOOL_FREERTOS = 0x20 # TCP component
FREERTOS_1 = 0x21 # UDP component
FREERTOS_2_CHERI = 0x22 # UDP component
FREERTOS_3 = 0x23 # UDP component
DEBIAN_1 = 0x24 # FPGA running Debian
DEBIAN_2_LMCO = 0x25 # FPGA running Debian
DEBIAN_3 = 0x26 # FPGA running Debian
TEENSY = 0x27 # TODO: how to monitor?
BESSPIN_TOOL_DEBIAN = 0x28 # TCP component
IGNITION = 0x30 # TCP component
LED_COMPONENT = 0x31 # Critical sub-component of Ignition
CAN_DISPLAY_FRONTEND = 0x32 # service component
CAN_DISPLAY_BACKEND = 0x33 # TCP component
PEDAL_MONITOR = 0x34 # Non-Critical sub-component of Ignition
JOYSTICK_MONITOR = 0x35 # Non-Critical sub-component of Ignition
INSTRUMENT_CLUSTER = 0x36 # Non-Critical sub-component of Ignition
HACKER_KIOSK_FRONTEND = 0x40 # service component
HACKER_KIOSK_BACKEND = 0x41 # TCP component
HACK_NONE = 0x50 # type of hack
HACK_OTA = 0x51 # type of hack
HACK_BRAKE = 0x51 # type of hack
HACK_THROTTLE = 0x52 # type of hack
HACK_TRANSMISSION = 0x53 # type of hack
HACK_LKAS = 0x54 # type of hack
HACK_INFOTAINMENT_VOLUME = 0x55 # Hacks info volume
HACK_INFOTAINMENT_MUSIC = 0x56 # Hacks info music
INFOTAINMENT_THIN_CLIENT = 0x60 # service component
INFOTAINMENT_SERVER_1 = 0x61 # UDP component
INFOTAINMENT_SERVER_2 = 0x62 # UDP component
INFOTAINMENT_SERVER_3 = 0x63 # UDP component
OTA_UPDATE_SERVER_1 = 0x64 # HTTP component
OTA_UPDATE_SERVER_2 = 0x65 # HTTP component
OTA_UPDATE_SERVER_3 = 0x66 # HTTP component
INFOTAINMENT_BACKEND = 0x67 # TCP component
SENSOR_THROTTLE = 0xBE # Throttle sensor error (From FreeRTOS ECU)
SENSOR_BRAKE = 0xBF # Brake sensor error (From FreeRTOS ECU)
ERROR_UNSPECIFIED = 0xF0 # General error
ERROR_NONE = 0xFF # No error (clears errors)

CanlibComponentNames = {
	BUTTON_STATION_1: "BUTTON_STATION_1",
	BUTTON_STATION_2: "BUTTON_STATION_2",
	BUTTON_STATION_3: "BUTTON_STATION_3",
	BUTTON_VOLUME_DOWN: "BUTTON_VOLUME_DOWN",
	BUTTON_VOLUME_UP: "BUTTON_VOLUME_UP",
	SCENARIO_BASELINE: "SCENARIO_BASELINE",
	SCENARIO_SECURE_INFOTAINMENT: "SCENARIO_SECURE_INFOTAINMENT",
	SCENARIO_SECURE_ECU: "SCENARIO_SECURE_ECU",
	FUNCTIONALITY_NONE: "FUNCTIONALITY_NONE",
	FUNCTIONALITY_MINIMAL: "FUNCTIONALITY_MINIMAL",
	FUNCTIONALITY_MEDIUM: "FUNCTIONALITY_MEDIUM",
	FUNCTIONALITY_FULL: "FUNCTIONALITY_FULL",
	BESSPIN_TOOL_FREERTOS: "BESSPIN_TOOL_FREERTOS",
	FREERTOS_1: "FREERTOS_1",
	FREERTOS_2_CHERI: "FREERTOS_2_CHERI",
	FREERTOS_3: "FREERTOS_3",
	DEBIAN_1: "DEBIAN_1",
	DEBIAN_2_LMCO: "DEBIAN_2_LMCO",
	DEBIAN_3: "DEBIAN_3",
	TEENSY: "TEENSY",
	BESSPIN_TOOL_DEBIAN: "BESSPIN_TOOL_DEBIAN",
	IGNITION: "IGNITION",
	LED_COMPONENT: "LED_COMPONENT",
	CAN_DISPLAY_FRONTEND: "CAN_DISPLAY_FRONTEND",
	CAN_DISPLAY_BACKEND: "CAN_DISPLAY_BACKEND",
	PEDAL_MONITOR: "PEDAL_MONITOR",
	JOYSTICK_MONITOR: "JOYSTICK_MONITOR",
	INSTRUMENT_CLUSTER: "INSTRUMENT_CLUSTER",
	HACKER_KIOSK_FRONTEND: "HACKER_KIOSK_FRONTEND",
	HACKER_KIOSK_BACKEND: "HACKER_KIOSK_BACKEND",
	HACK_NONE: "HACK_NONE",
	HACK_OTA: "HACK_OTA",
	HACK_BRAKE: "HACK_BRAKE",
	HACK_THROTTLE: "HACK_THROTTLE",
	HACK_TRANSMISSION: "HACK_TRANSMISSION",
	HACK_LKAS: "HACK_LKAS",
	HACK_INFOTAINMENT_VOLUME: "HACK_INFOTAINMENT_VOLUME",
	HACK_INFOTAINMENT_MUSIC: "HACK_INFOTAINMENT_MUSIC",
	INFOTAINMENT_THIN_CLIENT: "INFOTAINMENT_THIN_CLIENT",
	INFOTAINMENT_SERVER_1: "INFOTAINMENT_SERVER_1",
	INFOTAINMENT_SERVER_2: "INFOTAINMENT_SERVER_2",
	INFOTAINMENT_SERVER_3: "INFOTAINMENT_SERVER_3",
	OTA_UPDATE_SERVER_1: "OTA_UPDATE_SERVER_1",
	OTA_UPDATE_SERVER_2: "OTA_UPDATE_SERVER_2",
	OTA_UPDATE_SERVER_3: "OTA_UPDATE_SERVER_3",
	INFOTAINMENT_BACKEND: "INFOTAINMENT_BACKEND",
	SENSOR_THROTTLE: "SENSOR_THROTTLE",
	SENSOR_BRAKE: "SENSOR_BRAKE",
	ERROR_UNSPECIFIED: "ERROR_UNSPECIFIED",
	ERROR_NONE: "ERROR_NONE",
}

CanlibComponentIds = {
	"BUTTON_STATION_1": BUTTON_STATION_1,
	"BUTTON_STATION_2": BUTTON_STATION_2,
	"BUTTON_STATION_3": BUTTON_STATION_3,
	"BUTTON_VOLUME_DOWN": BUTTON_VOLUME_DOWN,
	"BUTTON_VOLUME_UP": BUTTON_VOLUME_UP,
	"SCENARIO_BASELINE": SCENARIO_BASELINE,
	"SCENARIO_SECURE_INFOTAINMENT": SCENARIO_SECURE_INFOTAINMENT,
	"SCENARIO_SECURE_ECU": SCENARIO_SECURE_ECU,
	"FUNCTIONALITY_NONE": FUNCTIONALITY_NONE,
	"FUNCTIONALITY_MINIMAL": FUNCTIONALITY_MINIMAL,
	"FUNCTIONALITY_MEDIUM": FUNCTIONALITY_MEDIUM,
	"FUNCTIONALITY_FULL": FUNCTIONALITY_FULL,
	"BESSPIN_TOOL_FREERTOS": BESSPIN_TOOL_FREERTOS,
	"FREERTOS_1": FREERTOS_1,
	"FREERTOS_2_CHERI": FREERTOS_2_CHERI,
	"FREERTOS_3": FREERTOS_3,
	"DEBIAN_1": DEBIAN_1,
	"DEBIAN_2_LMCO": DEBIAN_2_LMCO,
	"DEBIAN_3": DEBIAN_3,
	"TEENSY": TEENSY,
	"BESSPIN_TOOL_DEBIAN": BESSPIN_TOOL_DEBIAN,
	"IGNITION": IGNITION,
	"LED_COMPONENT": LED_COMPONENT,
	"CAN_DISPLAY_FRONTEND": CAN_DISPLAY_FRONTEND,
	"CAN_DISPLAY_BACKEND": CAN_DISPLAY_BACKEND,
	"PEDAL_MONITOR": PEDAL_MONITOR,
	"JOYSTICK_MONITOR": JOYSTICK_MONITOR,
	"INSTRUMENT_CLUSTER": INSTRUMENT_CLUSTER,
	"HACKER_KIOSK_FRONTEND": HACKER_KIOSK_FRONTEND,
	"HACKER_KIOSK_BACKEND": HACKER_KIOSK_BACKEND,
	"HACK_NONE": HACK_NONE,
	"HACK_OTA": HACK_OTA,
	"HACK_BRAKE": HACK_BRAKE,
	"HACK_THROTTLE": HACK_THROTTLE,
	"HACK_TRANSMISSION": HACK_TRANSMISSION,
	"HACK_LKAS": HACK_LKAS,
	"HACK_INFOTAINMENT_VOLUME": HACK_INFOTAINMENT_VOLUME,
	"HACK_INFOTAINMENT_MUSIC": HACK_INFOTAINMENT_MUSIC,
	"INFOTAINMENT_THIN_CLIENT": INFOTAINMENT_THIN_CLIENT,
	"INFOTAINMENT_SERVER_1": INFOTAINMENT_SERVER_1,
	"INFOTAINMENT_SERVER_2": INFOTAINMENT_SERVER_2,
	"INFOTAINMENT_SERVER_3": INFOTAINMENT_SERVER_3,
	"OTA_UPDATE_SERVER_1": OTA_UPDATE_SERVER_1,
	"OTA_UPDATE_SERVER_2": OTA_UPDATE_SERVER_2,
	"OTA_UPDATE_SERVER_3": OTA_UPDATE_SERVER_3,
	"INFOTAINMENT_BACKEND": INFOTAINMENT_BACKEND,
	"SENSOR_THROTTLE": SENSOR_THROTTLE,
	"SENSOR_BRAKE": SENSOR_BRAKE,
	"ERROR_UNSPECIFIED": ERROR_UNSPECIFIED,
	"ERROR_NONE": ERROR_NONE,
}
