name: CI
on: [push, pull_request]

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-strict: false
      - run: echo "hello world"
      - uses: ./.github/docker
        with:
          run: |
            echo user is $USER
            echo home is $HOME
            export PATH=/opt/Xilinx/Vivado/2019.1/bin:/opt/Xilinx/Vivado_Lab/2019.1/bin:$PATH
            . /opt/Xilinx/Vivado_Lab/2019.1/settings64.sh
            eval $(ssh-agent -s)
            ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
            . /home/besspinuser/.nix-profile/etc/profile.d/nix.sh
            nix-shell --command "./ci/fett-ci.py runOnPush push-${{ github.sha }}"
