name: CI
on: [push, pull_request]

jobs:
  Push:
    runs-on: self-hosted
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: ./.github/docker
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          run: nix-shell --command "./ci/fett-ci.py runOnPush push-${{ github.sha }}"
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: push-${{ github.sha }}
          path: "*-push-${{ github.sha }}"

  DevPR:
    runs-on: self-hosted
    strategy:
      matrix:
        index: [1, 2, 3, 4, 5]

    if: "github.event_name == 'pull_request' && github.base_ref == 'develop'"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: ./.github/docker
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          run: nix-shell --command "./ci/fett-ci.py runDevPR devPR-${{ github.sha }} -i ${{ matrix.index }} -N 5"
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: devPR-${{ github.sha }}
          path: "*-devPR-${{ github.sha }}"
