name: CI
on: [push, pull_request]

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: echo "hello world"
      - uses: ./.github/docker
