name: CI
on: [push, pull_request]

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${ secrets.MY_GITHUB_TOKEN }
          ssh-strict: false
      - run: echo "hello world"
      - uses: ./.github/docker
