name: CI
on: [push, pull_request]

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-strict: false
      - run: echo "hello world"
      - uses: ./.github/docker
        with:
          run: |
            echo "Hello world"
            echo "This is running inside the docker container"
            cat ~/.nix-profile/manifest.nix
