name: CI
on: [push, pull_request]

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: echo "hello world"
      - uses: ./.github/docker
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          run: nix-shell --command "./ci/fett-ci.py runOnPush push-${{ github.sha }}"
