name: CI DevPR
on:
  pull_request:
    branches:
      - develop

jobs:
  DevPR:
    runs-on: ${{ matrix.cfg.host }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: unix, index: 1, total: 2, host: docker-fpga }
          - { os: unix, index: 2, total: 2, host: docker-fpga }
          - { os: freertos, index: 1, total: 2, host: docker-fpga-io }
          - { os: freertos, index: 2, total: 2, host: docker-fpga-io }

    steps:
      - name: Remove lock file if it exists to prevent git fetch failures
        run: find .git -name index.lock -print -exec rm -f {} +
        continue-on-error: true
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          lfs: true
      - uses: ./.github/action
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          run: nix-shell --command "./ci/fett-ci.py runDevPR-${{ matrix.cfg.os }} -ep OnPrem -art devPR-${{ matrix.cfg.os }}-${{ github.sha }} -i ${{ matrix.cfg.index }} -N ${{ matrix.cfg.total }}"
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: devPR-${{ github.sha }}
          path: "*-devPR-${{ matrix.cfg.os }}-${{ github.sha }}"
