name: CI Push
on: [push]

jobs:
  Push:
    runs-on: docker-fpga
    steps:
      - name: Remove lock file if it exists to prevent git fetch failures
        run: find .git -name index.lock -print -exec rm -f {} +
        continue-on-error: true
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          lfs: true
      - uses: ./.github/action
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          run: nix-shell --command "./ci/fett-ci.py runOnPush -ep OnPrem -art push-${{ github.sha }}"
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: push-${{ github.sha }}
          path: "*-push-${{ github.sha }}"
