name: Scheduled Runs
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Periodic:
    runs-on: self-hosted
    strategy:
      matrix:
        index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: ./.github/docker
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          run: nix-shell --command "./ci/fett-ci.py runPeriodic periodic-${{ github.sha }} -i ${{ matrix.index }} -N 17"
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: periodic-${{ github.sha }}
          path: "*-periodic-${{ github.sha }}"

  Release:
    if: true == false
    runs-on: self-hosted
    strategy:
      matrix:
        index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: ./.github/docker
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          run: nix-shell --command "./ci/fett-ci.py runRelease release-${{ github.sha }} -i ${{ matrix.index }} -N 17"
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: release-${{ github.sha }}
          path: "*-release-${{ github.sha }}"
